source 'https://rubygems.org'

gem 'rails'
gem 'bootstrap-sass'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'sdoc'
gem 'nokogiri'
gem 'puma'
gem 'figaro'
gem 'capistrano'
gem 'capistrano-rvm'
gem 'capistrano3-puma'
gem 'capistrano-figaro'
gem 'capistrano-rails'
gem 'capistrano-bundler'
gem 'mini_racer'
gem 'pg'
gem 'omniauth-steam'
gem 'omniauth-rails_csrf_protection'
gem 'rexml'
gem 'steam-condenser'
gem 'netaddr'
gem 'record_tag_helper'
gem 'omniauth-discord'
gem 'omniauth-bnet'
gem 'omniauth-twitch'
gem 'listen'
gem 'ed25519'
gem 'bcrypt_pbkdf'

group :development do
  #gem 'sqlite3'
  gem 'byebug'
  gem 'web-console'
  gem 'spring'
end

group :production, :test do
  gem 'whenever', :require => false
end
